version: '3.7'
services:
  haproxy:
      image: haproxy-challenge:latest
      networks:
        - test
      ports:
        - 80:80
        - 443:443
  nginx:
      image: nginx:latest
      networks:
        - test                                    
      volumes: 
        - nginx-data:/usr/share/nginx/html/:rw

networks:
  test:
    driver: overlay
    attachable: true

volumes:
  nginx-data:
    external: true

