# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
version: 2.1
jobs:
  build:
    docker:
      - image: davidcorino/haproxy:3.0
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          docker build -t davidcorino/haproxy:3.0 .
